version: '3.8'

services:
  datalake_db:
    image: postgres:14-alpine
    container_name: datalake_db
    restart: always
    environment:
      POSTGRES_USER: aiops_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aiops_data
    volumes:
      - aiops_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Optional: Expose port for debugging/external connection
    networks:
      - aiops_network

networks:
  aiops_network:
    external: true
    name: aiops-stack_aiops-network

volumes:
  aiops_postgres_data:
    external: true
