global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus itself (Target 1: Stable)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  # SCRAPE HOST VM (Node Exporter - Target 2: Using the external host IP)
  - job_name: 'node_exporter_host'
    static_configs:
      - targets: ['192.168.206.136:9100']
